/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentacion;

import java.net.URL;
import javax.swing.ImageIcon;

/**
 *
 * @author iJona
 */
public class AcercaDe extends javax.swing.JFrame {

    /**
     * Creates new form Ayuda
     */
    public AcercaDe() {
        initComponents();
        cargarPantallaAcercaDe("/imagenes/fondoAcercaDe.png");
        habilitarPantallaSintaxis(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        areaT1 = new javax.swing.JTextArea();
        areaT2 = new javax.swing.JTextArea();
        areaT3 = new javax.swing.JTextArea();
        botonSintax = new javax.swing.JToggleButton();
        botonOther = new javax.swing.JButton();
        botonTablas = new javax.swing.JButton();
        botonRegistros = new javax.swing.JButton();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        areaT1.setEditable(false);
        areaT1.setColumns(5);
        areaT1.setLineWrap(true);
        areaT1.setRows(5);
        areaT1.setText("CREAR TABLA nombre_tabla CAMPOS campo1, campoN CLAVE campo1 LONGITUD numEntero"); // NOI18N
        areaT1.setToolTipText("");
        areaT1.setBorder(null);
        areaT1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        getContentPane().add(areaT1, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 204, 270, 40));

        areaT2.setEditable(false);
        areaT2.setColumns(5);
        areaT2.setLineWrap(true);
        areaT2.setRows(5);
        areaT2.setText("MODIFICAR TABLA nombre_tabla CAMPO nombre_campo POR nombre_campo"); // NOI18N
        areaT2.setToolTipText("");
        areaT2.setBorder(null);
        areaT2.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        getContentPane().add(areaT2, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 308, 270, 40));

        areaT3.setEditable(false);
        areaT3.setColumns(5);
        areaT3.setLineWrap(true);
        areaT3.setRows(5);
        areaT3.setText("ELIMINAR TABLA nombre_tabla"); // NOI18N
        areaT3.setToolTipText("");
        areaT3.setBorder(null);
        areaT3.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        getContentPane().add(areaT3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 425, 250, 30));

        botonSintax.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/botonSintax.png"))); // NOI18N
        botonSintax.setBorder(null);
        botonSintax.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSintaxActionPerformed(evt);
            }
        });
        getContentPane().add(botonSintax, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 89, 33));

        botonOther.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/botonSintaxOtros.png"))); // NOI18N
        botonOther.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonOtherActionPerformed(evt);
            }
        });
        getContentPane().add(botonOther, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 90, 80, 33));

        botonTablas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/botonSintaxTab.png"))); // NOI18N
        botonTablas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonTablasActionPerformed(evt);
            }
        });
        getContentPane().add(botonTablas, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 80, 33));

        botonRegistros.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/botonSintaxReg.png"))); // NOI18N
        botonRegistros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRegistrosActionPerformed(evt);
            }
        });
        getContentPane().add(botonRegistros, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 90, 80, 33));
        getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 300, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonSintaxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSintaxActionPerformed
        // TODO add your handling code here:
         
        if( !botonSintax.isSelected()){
           // fondo.setIcon(icon);
           cargarPantallaAcercaDe("/imagenes/fondoAcercaDe.png");
            habilitarPantallaSintaxis(false);
            
        }
        else{
            cargarPantallaAcercaDe("/imagenes/fondoSintaxTab.png");
            habilitarPantallaSintaxis(true);
            llenarCajaSintaxis("TABLAS");
        }
        
    }//GEN-LAST:event_botonSintaxActionPerformed

    private void botonTablasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonTablasActionPerformed
        // TODO add your handling code here:
        cargarPantallaAcercaDe("/imagenes/fondoSintaxTab.png");
        habilitarPantallaSintaxis(true);
        llenarCajaSintaxis("TABLAS");
        
    }//GEN-LAST:event_botonTablasActionPerformed

    private void botonRegistrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRegistrosActionPerformed
        // TODO add your handling code here:
        cargarPantallaAcercaDe("/imagenes/fondoSintaxReg.png");
        habilitarPantallaSintaxis(true);
        llenarCajaSintaxis("REGISTROS");
    }//GEN-LAST:event_botonRegistrosActionPerformed

    private void botonOtherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonOtherActionPerformed
        // TODO add your handling code here:
        cargarPantallaAcercaDe("/imagenes/fondoSintaxOtros.png");
        habilitarPantallaSintaxis(true);
        llenarCajaSintaxis("OTROS");
    }//GEN-LAST:event_botonOtherActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AcercaDe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AcercaDe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AcercaDe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AcercaDe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AcercaDe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea areaT1;
    private javax.swing.JTextArea areaT2;
    private javax.swing.JTextArea areaT3;
    private javax.swing.JButton botonOther;
    private javax.swing.JButton botonRegistros;
    private javax.swing.JToggleButton botonSintax;
    private javax.swing.JButton botonTablas;
    private javax.swing.JLabel fondo;
    // End of variables declaration//GEN-END:variables

    private void habilitarPantallaSintaxis(boolean valor) {
        botonOther.setVisible(valor);
        botonRegistros.setVisible(valor);
        botonTablas.setVisible(valor);
        areaT1.setVisible(valor);
        areaT2.setVisible(valor);
        areaT3.setVisible(valor);
        areaT1.setWrapStyleWord(true);
        areaT2.setWrapStyleWord(true);
        areaT3.setWrapStyleWord(true);
    }

    private void cargarPantallaAcercaDe(String ruta) {
            URL url = this.getClass().getResource(ruta);
            ImageIcon icon = new ImageIcon(url);
            fondo.setIcon(icon);
    }

    private void llenarCajaSintaxis(String tipo) {
        String a1="", a2="" ,a3="" ;
        if(tipo.equals("TABLAS")){
            a1="CREAR TABLA nombreTabla CAMPOS campo1, ..., campoN CLAVE campo1 LONGITUD nEntero";
            a2="MODIFICAR TABLA nombreTabla CAMPO nombreCampo POR nuevoNombreCampo";
            a3="ELIMINAR TABLA nombreTabla";
            
        }
        else if(tipo.equals("REGISTROS")){
            a1="CREAR REGISTRO nombreTabla VALOR vCampo1, vCampo2, ..., vCampoN";
            a2="MODIFICAR REGISTRO nomTabla CLAVE valorClave CAMPO campo POR valorNuevo";
            a3="ELIMINAR REGISTRO nombreTabla CLAVE valorCampoClave";
        }
        else if(tipo.equals("OTROS")){
            a1="SELECCIONAR DE nombreTabla DONDE nombreCampo = \"Algo\"";
            a2="UNIR nombreTabla1, nombreTabla2 POR nombreCampo";
            areaT3.setVisible(false);
        }
        areaT1.setText(a1);
        areaT2.setText(a2);
        areaT3.setText(a3);
    }
}
